### ISSUE TITLE
Review existing prototype

### ISSUE THREAD

**Issue by scottchen98** [Vero-Ventures/insurance-calculator#1]
- review the existing insurance calculator to understand its functionalities, limitations, and potential for improvement. 
- understand its functionalities, limitations, and identify areas for improvement to inform development plans for the upcoming sprint.

[Dynamic Needs Analysis](https://dynamic-needs-analysis.vercel.app/auth)

**Comment by m-a-s-h-e-d** [comment]
Team has reviewed the existing calculator prototype and taken them into consideration for our Figma design wireframes.
