### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by scottchen98** [Vero-Ventures/insurance-calculator#6]
- Briefly explain the initial goals and objectives set for the insurance calculator project.
- Demonstrate the core functionalities implemented in the MVP (e.g., profile management, basic advisor recommendations, payment integration, etc.). 
- Showcase the designed user interface (UI) of the application and walk through the user flow for key functionalities. 
- Discuss any significant challenges encountered during development and how the team tackled them.
- Outline potential next steps and future development plans for the insurance calculator app.

**Comment by nng32** [comment]
Significant challenges to be excluded due to supervisor request
